---
title: "HW5-2DONE"
author: "Kedree Proffitt"
date: "2022-08-03"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Imports

```{r}
    library(maps) # Obligatory Imports
    library(mapdata)
    library(ggplot2)
    library(dplyr)
```

## Data Imports

```{r}
    setwd("C:/Users/Kedree Proffitt/Downloads") # Set Working directory
    states <- map_data("state") # Get our mapping data
    load(file='wind_turbines.rda') # Get our turbine data
```

## Data Filtering

```{r}
    # We only want to represent California
    states <- states %>% filter(region=="california") # Take only California mapping data
    wind_ca <- wind_turbines %>% filter(t_state == "CA") # Take only the California turbines
```

## Data Visualization

```{r}
    ggplot(states, aes(long, lat)) +
      geom_polygon() +
      geom_point(wind_ca, colour = "red", size = 1.5, mapping=aes(xlong, ylat)) +
      coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
      ggtitle("Wind Turbines In California") +
      xlab("") + ylab("") +
      theme(axis.text.x = element_blank(), axis.ticks = element_blank()) +
      theme(axis.text.y = element_blank(), axis.ticks = element_blank())
```
